from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field


class ActivityResponse(BaseModel):
    id: UUID
    project_id: UUID | None
    actor_id: UUID
    action: str = Field(max_length=100)
    entity_type: str = Field(max_length=50)
    entity_id: UUID
    metadata: dict[str, Any]
    created_at: datetime

    model_config = {
        "from_attributes": True
    }
    
    #For activities, we don't include a create schema because activities are generated by the system rather than created directly by users.