from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


class NotificationResponse(BaseModel):
    id: UUID
    recipient_id: UUID
    type: str = Field(max_length=50)
    message: str
    entity_type: str = Field(max_length=50)
    entity_id: UUID
    read_at: datetime | None
    created_at: datetime

    model_config = {
        "from_attributes": True
    }
    
    #For notifications, we don't include a create schema because notifications are generated by the system rather than created directly by users.